name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Endre til navnet på hovedgrenen din hvis den er annerledes
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Samme her

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: ./prosjek1
        run: npm install

      - name: Build application
        working-directory: ./prosjek1
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SKY_03D4D8D1E }}
          action: 'upload'
          app_location: './prosjek1/dist'  # Sti til den bygde applikasjonen
          api_location: ''  # Hvis du ikke har en API, la denne være tom
          skip_app_build: true  # Vi har allerede bygget appen manuelt