name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Endre til navnet på hovedgrenen din hvis den er annerledes
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Samme her

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Dette er automatisk tilgjengelig
          action: 'upload'
          app_location: './prosjek1'  # Sti til applikasjonsmappen din
          api_location: ''  # Hvis du ikke har en API, la denne være tom
          output_location: 'dist'  # Output-mappen etter bygging (endre fra 'build' til 'dist')